name: 标签翻译
description: 讨论标签翻译的增加和修改
title: "[添加/更改]标签 - [标签]"
labels: ["翻译"]
body:
  - type: input
    id: name
    attributes:
      label: 名称
      description: 输入标签的中文翻译
    validations:
      required: true
  - type: textarea
    id: intro
    attributes:
      label: 描述
      description: 输入标签的描述 <https://github.com/EhTagTranslation/Database/wiki/%E5%8F%82%E4%B8%8E%E7%BF%BB%E8%AF%91#markdown-%E4%B9%A6%E5%86%99%E6%8C%87%E5%BC%95>
    validations:
      required: false
  - type: textarea
    id: links
    attributes:
      label: 外部链接
      description: 输入标签的相关链接，如指向 EhWiki 页面或萌百词条的链接
    validations:
      required: false
  - type: textarea
    id: comment
    attributes:
      label: 备注
      description: 关于该变更的额外说明
    validations:
      required: false
